ALTER TABLE users 
ADD COLUMN full_name VARCHAR(255),
ADD COLUMN dob DATE,
ADD COLUMN gender VARCHAR(20),
ADD COLUMN phone VARCHAR(30),
ADD COLUMN address VARCHAR(255),
ADD COLUMN national_id VARCHAR(50),
ADD COLUMN emergency_contact VARCHAR(255); 